---
all:
  hosts:
    web1:
      ansible_user: StringerManSyd
      ansible_port: 22
      ansible_host: 10.0.0.5
      ansible_ssh_private_key_file: /etc/ansible/id_rsa
      ansible_python_interpreter: /usr/bin/python3
